version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      # Variabel yang sudah ada
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      DEFAULT_SCHEMA: ${DEFAULT_SCHEMA}

      # Encryption settings
      ENCRYPTION_RESPONSE: ${ENCRYPTION_RESPONSE}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_IV: ${ENCRYPTION_IV}

      # Development features
      ENABLE_TENANT_MANAGEMENT: ${ENABLE_TENANT_MANAGEMENT}

      # Tambahan untuk konfigurasi email
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SSL_TLS: ${MAIL_SSL_TLS}
      MAIL_STARTTLS: ${MAIL_STARTTLS}
