version: '3.8'

services:
  # Atask API Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atask_app
    ports:
      - "8000:8000"
    environment:
      # Application Settings
      APP_NAME: ${APP_NAME:-atask}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      DEBUG: ${DEBUG:-false}

      # Database Configuration (Cloud Database)
      DATABASE_URL: ${DATABASE_URL}

      # Atlas SSO (ATAMS) Configuration
      ATLAS_SSO_URL: ${ATLAS_SSO_URL}
      ATLAS_APP_CODE: ${ATLAS_APP_CODE:-ATASK}
      ATLAS_ENCRYPTION_KEY: ${ATLAS_ENCRYPTION_KEY}
      ATLAS_ENCRYPTION_IV: ${ATLAS_ENCRYPTION_IV}

      # Response Encryption (Optional)
      ENCRYPTION_ENABLED: ${ENCRYPTION_ENABLED:-false}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_IV: ${ENCRYPTION_IV}

      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS}

      # Logging Configuration
      LOGGING_ENABLED: ${LOGGING_ENABLED:-true}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_TO_FILE: ${LOG_TO_FILE:-false}

      # Rate Limiting
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60}

    volumes:
      # Mount logs directory if LOG_TO_FILE is enabled
      - ./logs:/app/logs
      # Mount uploads directory for future attachment feature
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - atask_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  atask_network:
    driver: bridge
