version: '3.8'

services:
  # Atask API Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atask_app
    ports:
      - "8000:8000"
    environment:
      # Application Settings
      APP_NAME: ${APP_NAME:-atask}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      DEBUG: ${DEBUG:-false}

      # Database Configuration (Cloud Database)
      DATABASE_URL: ${DATABASE_URL}

      # Atlas SSO (ATAMS) Configuration
      ATLAS_SSO_URL: ${ATLAS_SSO_URL}
      ATLAS_APP_CODE: ${ATLAS_APP_CODE:-ATASK}
      ATLAS_ENCRYPTION_KEY: ${ATLAS_ENCRYPTION_KEY}
      ATLAS_ENCRYPTION_IV: ${ATLAS_ENCRYPTION_IV}

      # Cloudinary Configuration
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER:-atask}

      # Email Configuration
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Atask Notification}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_USE_TLS: ${MAIL_USE_TLS:-true}
      MAIL_USE_SSL: ${MAIL_USE_SSL:-false}

      # Frontend URL for tracking links
      APP_URL: ${APP_URL}

      # Cron API Key for securing scheduled endpoints
      CRON_API_KEY: ${CRON_API_KEY}

      # Response Encryption (Optional)
      ENCRYPTION_ENABLED: ${ENCRYPTION_ENABLED:-false}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_IV: ${ENCRYPTION_IV}

      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS}

      # Logging Configuration
      LOGGING_ENABLED: ${LOGGING_ENABLED:-true}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_TO_FILE: ${LOG_TO_FILE:-false}

      # Rate Limiting
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60}

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
